name: Run Tests and Report Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Test on a set of relevant Python versions
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Run tests with coverage
      run: |
        pytest --cov=simsig --cov-report=xml

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        # The GITHUB_TOKEN is automatically provided by GitHub Actions.
        # It's used to identify the repository and the commit.
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Notify Coveralls that this is part of a parallel build
        parallel: true

  # This job will run only after all jobs in the 'test' matrix have completed successfully
  coveralls-finish:
    needs: test # This job depends on the 'test' job
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        # Also pass the token to the finishing job
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Send the signal to finalize the parallel build
        parallel-finished: true
